bpm = 120
keypress("O", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(2, bpm)
keypress("I", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(2, bpm)
keypress("u", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(2, bpm)
keypress("Y", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(2, bpm)
keypress("Y", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(3, bpm)
keypress("u", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(4, bpm)
keypress("u", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(4, bpm)
keypress("Y", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(2, bpm)
keypress("Y", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(3, bpm)
keypress("u", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(3, bpm)
keypress("u", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(5, bpm)
keypress("Y", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(2, bpm)
keypress("Y", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(3, bpm)
keypress("u", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(4, bpm)
keypress("u", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(4, bpm)
keypress("Y", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(2, bpm)
keypress("Y", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(3, bpm)
keypress("u", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(3, bpm)
keypress("I", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(3, bpm)
keypress("u", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(2, bpm)
keypress("Y", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(2, bpm)
keypress("Y", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(3, bpm)
keypress("u", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(3, bpm)
keypress("u", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(5, bpm)
keypress("Y", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(2, bpm)
keypress("Y", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(3, bpm)
keypress("u", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(3, bpm)
keypress("u", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(5, bpm)
keypress("Y", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(2, bpm)
keypress("Y", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(3, bpm)
keypress("u", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(4, bpm)
keypress("u", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(4, bpm)
keypress("Y", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(2, bpm)
keypress("Y", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(3, bpm)
keypress("u", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
