bpm = 130
keypress("T", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("(", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("(", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("(", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("W", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("r", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("W", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("(", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("W", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("r", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("(", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("W", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("r", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("W", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("(", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("W", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("r", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("(", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("(", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("7", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
