bpm = 130
keypress("T", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("7", x, bpm)
keypress("e", x, bpm)
keypress("(", x, bpm)
keypress("*", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("!", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)
keypress("$", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("$", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("@", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.417, bpm)
keypress("^", x, bpm)
keypress("$", x, bpm)
rest(0.083, bpm)
keypress("$", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("r", x, bpm)
keypress("9", x, bpm)
keypress("@", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.417, bpm)
keypress("^", x, bpm)
keypress("$", x, bpm)
rest(0.083, bpm)
keypress("W", x, bpm)
keypress("$", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("$", x, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
keypress("@", x, bpm)
rest(0.167, bpm)
keypress("^", x, bpm)
keypress("$", x, bpm)
rest(0.083, bpm)
keypress("e", x, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("!", x, bpm)
keypress("$", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)
keypress("$", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("e", x, bpm)
keypress("$", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("@", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.417, bpm)
keypress("^", x, bpm)
keypress("$", x, bpm)
rest(0.083, bpm)
keypress("$", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("@", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.417, bpm)
keypress("^", x, bpm)
keypress("$", x, bpm)
rest(0.083, bpm)
keypress("W", x, bpm)
keypress("$", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("$", x, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
keypress("@", x, bpm)
rest(0.167, bpm)
keypress("^", x, bpm)
keypress("$", x, bpm)
rest(0.083, bpm)
keypress("e", x, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("!", x, bpm)
keypress("$", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("7", x, bpm)
keypress("e", x, bpm)
keypress("(", x, bpm)
keypress("*", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("!", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)
keypress("$", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("$", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("@", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.417, bpm)
keypress("^", x, bpm)
keypress("$", x, bpm)
rest(0.083, bpm)
keypress("$", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("r", x, bpm)
keypress("9", x, bpm)
keypress("@", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.417, bpm)
keypress("^", x, bpm)
keypress("$", x, bpm)
rest(0.083, bpm)
keypress("W", x, bpm)
keypress("$", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("$", x, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
keypress("@", x, bpm)
rest(0.167, bpm)
keypress("^", x, bpm)
keypress("$", x, bpm)
rest(0.083, bpm)
keypress("e", x, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("!", x, bpm)
keypress("$", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)
keypress("$", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("e", x, bpm)
keypress("$", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("@", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.417, bpm)
keypress("^", x, bpm)
keypress("$", x, bpm)
rest(0.083, bpm)
keypress("$", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("@", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.417, bpm)
keypress("^", x, bpm)
keypress("$", x, bpm)
rest(0.083, bpm)
keypress("W", x, bpm)
keypress("$", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("$", x, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
keypress("@", x, bpm)
keypress("j", x, bpm)
rest(0.167, bpm)
keypress("^", x, bpm)
keypress("$", x, bpm)
rest(0.083, bpm)
keypress("e", x, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("!", x, bpm)
keypress("$", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("7", x, bpm)
keypress("e", x, bpm)
keypress("(", x, bpm)
keypress("*", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("L", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("7", x, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("j", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("!", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)
keypress("$", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("$", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("@", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.417, bpm)
keypress("^", x, bpm)
keypress("$", x, bpm)
rest(0.083, bpm)
keypress("$", x, bpm)
keypress("f", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("r", x, bpm)
keypress("9", x, bpm)
keypress("@", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("G", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.417, bpm)
keypress("^", x, bpm)
keypress("$", x, bpm)
rest(0.083, bpm)
keypress("W", x, bpm)
keypress("$", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("$", x, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
keypress("j", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
keypress("@", x, bpm)
rest(0.167, bpm)
keypress("^", x, bpm)
keypress("$", x, bpm)
rest(0.083, bpm)
keypress("e", x, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("!", x, bpm)
keypress("$", x, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)
keypress("$", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("e", x, bpm)
keypress("$", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("@", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.417, bpm)
keypress("^", x, bpm)
keypress("$", x, bpm)
rest(0.083, bpm)
keypress("$", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("@", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.417, bpm)
keypress("^", x, bpm)
keypress("$", x, bpm)
rest(0.083, bpm)
keypress("W", x, bpm)
keypress("$", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("$", x, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
keypress("@", x, bpm)
rest(0.167, bpm)
keypress("^", x, bpm)
keypress("$", x, bpm)
rest(0.083, bpm)
keypress("e", x, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("!", x, bpm)
keypress("$", x, bpm)
keypress("G", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("7", x, bpm)
keypress("e", x, bpm)
keypress("(", x, bpm)
keypress("*", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("L", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("k", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("j", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("!", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)
keypress("$", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("$", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("@", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.417, bpm)
keypress("^", x, bpm)
keypress("$", x, bpm)
rest(0.083, bpm)
keypress("$", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("r", x, bpm)
keypress("9", x, bpm)
keypress("@", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("G", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.417, bpm)
keypress("^", x, bpm)
keypress("$", x, bpm)
rest(0.083, bpm)
keypress("W", x, bpm)
keypress("$", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("$", x, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
keypress("j", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
keypress("@", x, bpm)
rest(0.167, bpm)
keypress("^", x, bpm)
keypress("$", x, bpm)
rest(0.083, bpm)
keypress("e", x, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("!", x, bpm)
keypress("$", x, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)
keypress("$", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("e", x, bpm)
keypress("$", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("@", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.417, bpm)
keypress("^", x, bpm)
keypress("$", x, bpm)
rest(0.083, bpm)
keypress("$", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("@", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.417, bpm)
keypress("^", x, bpm)
keypress("$", x, bpm)
rest(0.083, bpm)
keypress("W", x, bpm)
keypress("$", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("$", x, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
keypress("@", x, bpm)
keypress("j", x, bpm)
rest(0.167, bpm)
keypress("^", x, bpm)
keypress("$", x, bpm)
rest(0.083, bpm)
keypress("e", x, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("!", x, bpm)
keypress("$", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("7", x, bpm)
keypress("e", x, bpm)
keypress("(", x, bpm)
keypress("*", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("L", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("7", x, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("j", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("!", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)
keypress("$", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("$", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("@", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.417, bpm)
keypress("^", x, bpm)
keypress("$", x, bpm)
rest(0.083, bpm)
keypress("$", x, bpm)
keypress("f", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("r", x, bpm)
keypress("9", x, bpm)
keypress("@", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("G", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.417, bpm)
keypress("^", x, bpm)
keypress("$", x, bpm)
rest(0.083, bpm)
keypress("W", x, bpm)
keypress("$", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("$", x, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
keypress("j", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
keypress("@", x, bpm)
rest(0.167, bpm)
keypress("^", x, bpm)
keypress("$", x, bpm)
rest(0.083, bpm)
keypress("e", x, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("!", x, bpm)
keypress("$", x, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("S", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("1", x, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)
keypress("$", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("e", x, bpm)
keypress("$", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("@", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.417, bpm)
keypress("^", x, bpm)
keypress("$", x, bpm)
rest(0.083, bpm)
keypress("$", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("@", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.417, bpm)
keypress("^", x, bpm)
keypress("$", x, bpm)
rest(0.083, bpm)
keypress("W", x, bpm)
keypress("$", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("$", x, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
keypress("@", x, bpm)
rest(0.167, bpm)
keypress("^", x, bpm)
keypress("$", x, bpm)
rest(0.083, bpm)
keypress("e", x, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("!", x, bpm)
keypress("$", x, bpm)
keypress("G", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("7", x, bpm)
keypress("e", x, bpm)
keypress("(", x, bpm)
keypress("*", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("L", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("k", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
keypress("k", x, bpm)
keypress("x", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("j", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("!", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("k", x, bpm)
keypress("L", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)
keypress("$", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("$", x, bpm)
keypress("j", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("@", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.417, bpm)
keypress("^", x, bpm)
keypress("$", x, bpm)
rest(0.083, bpm)
keypress("$", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("r", x, bpm)
keypress("9", x, bpm)
keypress("@", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
keypress("f", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("G", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.417, bpm)
keypress("^", x, bpm)
keypress("$", x, bpm)
rest(0.083, bpm)
keypress("W", x, bpm)
keypress("$", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("$", x, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
keypress("j", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
keypress("@", x, bpm)
rest(0.167, bpm)
keypress("^", x, bpm)
keypress("$", x, bpm)
rest(0.083, bpm)
keypress("e", x, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("!", x, bpm)
keypress("$", x, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("S", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)
keypress("$", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("e", x, bpm)
keypress("$", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("@", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.417, bpm)
keypress("^", x, bpm)
keypress("$", x, bpm)
rest(0.083, bpm)
keypress("$", x, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("@", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.417, bpm)
keypress("^", x, bpm)
keypress("$", x, bpm)
rest(0.083, bpm)
keypress("W", x, bpm)
keypress("$", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
keypress("u", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("$", x, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
keypress("@", x, bpm)
rest(0.167, bpm)
keypress("^", x, bpm)
keypress("$", x, bpm)
rest(0.083, bpm)
keypress("e", x, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("!", x, bpm)
keypress("$", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("7", x, bpm)
keypress("e", x, bpm)
keypress("(", x, bpm)
keypress("*", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
keypress("u", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("!", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)
keypress("$", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
keypress("T", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("$", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("@", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.417, bpm)
keypress("^", x, bpm)
keypress("$", x, bpm)
rest(0.083, bpm)
keypress("$", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("r", x, bpm)
keypress("9", x, bpm)
keypress("@", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.417, bpm)
keypress("^", x, bpm)
keypress("$", x, bpm)
rest(0.083, bpm)
keypress("W", x, bpm)
keypress("$", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("$", x, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
keypress("@", x, bpm)
rest(0.167, bpm)
keypress("^", x, bpm)
keypress("$", x, bpm)
rest(0.083, bpm)
keypress("e", x, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("!", x, bpm)
keypress("$", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)
keypress("$", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("e", x, bpm)
keypress("$", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("@", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.417, bpm)
keypress("^", x, bpm)
keypress("$", x, bpm)
rest(0.083, bpm)
keypress("$", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("@", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.417, bpm)
keypress("^", x, bpm)
keypress("$", x, bpm)
rest(0.083, bpm)
keypress("W", x, bpm)
keypress("$", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("$", x, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
keypress("@", x, bpm)
rest(0.167, bpm)
keypress("^", x, bpm)
keypress("$", x, bpm)
rest(0.083, bpm)
keypress("e", x, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("!", x, bpm)
keypress("$", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("7", x, bpm)
keypress("e", x, bpm)
keypress("(", x, bpm)
keypress("*", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("!", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)
keypress("$", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("$", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("@", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.417, bpm)
keypress("^", x, bpm)
keypress("$", x, bpm)
rest(0.083, bpm)
keypress("$", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("r", x, bpm)
keypress("9", x, bpm)
keypress("@", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.417, bpm)
keypress("^", x, bpm)
keypress("$", x, bpm)
rest(0.083, bpm)
keypress("W", x, bpm)
keypress("$", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("$", x, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
keypress("@", x, bpm)
rest(0.167, bpm)
keypress("^", x, bpm)
keypress("$", x, bpm)
rest(0.083, bpm)
keypress("e", x, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("!", x, bpm)
keypress("$", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)
keypress("$", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("e", x, bpm)
keypress("$", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("@", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.417, bpm)
keypress("^", x, bpm)
keypress("$", x, bpm)
rest(0.083, bpm)
keypress("$", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
keypress("@", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("4", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.417, bpm)
keypress("^", x, bpm)
keypress("$", x, bpm)
rest(0.083, bpm)
keypress("W", x, bpm)
keypress("$", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("$", x, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
keypress("@", x, bpm)
rest(0.167, bpm)
keypress("^", x, bpm)
keypress("$", x, bpm)
rest(0.083, bpm)
keypress("e", x, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("!", x, bpm)
keypress("$", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
