bpm = 151
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
rest(2, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
rest(2, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
