bpm = 110
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
rest(7, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
rest(4, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
keypress("(", x, bpm)
keypress("7", x, bpm)
rest(2, bpm)
keypress("H", x, bpm)
rest(2, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
rest(5, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("W", x, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
rest(4, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
keypress("(", x, bpm)
keypress("7", x, bpm)
rest(2, bpm)
keypress("H", x, bpm)
rest(2, bpm)
keypress("D", x, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("0", x, bpm)
keypress("7", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
keypress("*", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("0", x, bpm)
keypress("7", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
keypress("*", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
keypress("*", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(2.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(2, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
keypress("7", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(2, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
keypress("*", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(2, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
keypress("*", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(2.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(2, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
keypress("7", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(2, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
keypress("*", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(2, bpm)
keypress("D", x, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("0", x, bpm)
keypress("7", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("Q", x, bpm)
keypress("*", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("0", x, bpm)
keypress("7", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
keypress("*", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("6", x, bpm)
rest(3, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("k", x, bpm)
rest(4, bpm)
keypress("H", x, bpm)
keypress("0", x, bpm)
keypress("7", x, bpm)
keypress("%", x, bpm)
rest(3, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("j", x, bpm)
keypress("Q", x, bpm)
keypress("*", x, bpm)
keypress("6", x, bpm)
rest(2, bpm)
keypress("H", x, bpm)
rest(2, bpm)
keypress("H", x, bpm)
keypress("0", x, bpm)
keypress("*", x, bpm)
keypress("6", x, bpm)
rest(3, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("k", x, bpm)
rest(4, bpm)
keypress("H", x, bpm)
keypress("0", x, bpm)
keypress("7", x, bpm)
keypress("%", x, bpm)
rest(3, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("j", x, bpm)
keypress("Q", x, bpm)
keypress("*", x, bpm)
keypress("6", x, bpm)
rest(3, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
keypress("*", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("0", x, bpm)
keypress("7", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
keypress("*", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
keypress("*", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("0", x, bpm)
keypress("7", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
keypress("*", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
keypress("*", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(2.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(2, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
keypress("7", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(2, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
keypress("*", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(2, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
keypress("*", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(2.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(2, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
keypress("7", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(2, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
keypress("*", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(2, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
keypress("*", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("0", x, bpm)
keypress("7", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
keypress("*", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
keypress("*", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("0", x, bpm)
keypress("7", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
keypress("*", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
keypress("*", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(2.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(2, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
keypress("7", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(2, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
keypress("*", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(2, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
keypress("*", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(2.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(2, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
keypress("7", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(2, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
keypress("*", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(2, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
keypress("*", x, bpm)
keypress("6", x, bpm)
rest(3, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(4, bpm)
keypress("D", x, bpm)
keypress("0", x, bpm)
keypress("7", x, bpm)
keypress("%", x, bpm)
rest(3, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("Q", x, bpm)
keypress("*", x, bpm)
keypress("6", x, bpm)
rest(4, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
keypress("*", x, bpm)
keypress("6", x, bpm)
rest(3, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(4, bpm)
keypress("D", x, bpm)
keypress("0", x, bpm)
keypress("7", x, bpm)
keypress("%", x, bpm)
rest(3, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("Q", x, bpm)
keypress("*", x, bpm)
keypress("6", x, bpm)
