bpm = 73
keypress("8", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(2.5, bpm)
keypress("q", x, bpm)
rest(0.75, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(2.5, bpm)
keypress("8", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(2.5, bpm)
keypress("q", x, bpm)
rest(0.75, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(2.5, bpm)
keypress("8", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
keypress("Y", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("i", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("Y", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("%", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("%", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("%", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("i", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
keypress("Y", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.167, bpm)
keypress("T", x, bpm)
rest(0.167, bpm)
keypress("T", x, bpm)
rest(0.167, bpm)
keypress("i", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("i", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("Y", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("%", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("i", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.167, bpm)
keypress("Y", x, bpm)
rest(0.083, bpm)
keypress("8", x, bpm)
rest(0.083, bpm)
keypress("T", x, bpm)
rest(0.167, bpm)
keypress("$", x, bpm)
keypress("Y", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.167, bpm)
keypress("Y", x, bpm)
rest(0.167, bpm)
keypress("T", x, bpm)
rest(0.167, bpm)
keypress("Y", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.167, bpm)
keypress("Y", x, bpm)
rest(0.167, bpm)
keypress("T", x, bpm)
rest(0.167, bpm)
keypress("Y", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.167, bpm)
keypress("Y", x, bpm)
rest(0.167, bpm)
keypress("T", x, bpm)
rest(0.167, bpm)
keypress("Y", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.083, bpm)
keypress("T", x, bpm)
rest(0.167, bpm)
keypress("Y", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
rest(0.167, bpm)
keypress("Y", x, bpm)
rest(0.083, bpm)
keypress("q", x, bpm)
rest(0.083, bpm)
keypress("T", x, bpm)
rest(0.167, bpm)
keypress("8", x, bpm)
keypress("Y", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
rest(0.167, bpm)
keypress("Y", x, bpm)
rest(0.167, bpm)
keypress("T", x, bpm)
rest(0.167, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.167, bpm)
keypress("Y", x, bpm)
rest(0.167, bpm)
keypress("T", x, bpm)
rest(0.167, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.167, bpm)
keypress("Y", x, bpm)
rest(0.167, bpm)
keypress("T", x, bpm)
rest(0.167, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.083, bpm)
keypress("T", x, bpm)
rest(0.167, bpm)
keypress("Y", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.167, bpm)
keypress("Y", x, bpm)
rest(0.083, bpm)
keypress("8", x, bpm)
rest(0.083, bpm)
keypress("T", x, bpm)
rest(0.167, bpm)
keypress("$", x, bpm)
keypress("Y", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.167, bpm)
keypress("Y", x, bpm)
rest(0.167, bpm)
keypress("T", x, bpm)
rest(0.167, bpm)
keypress("Y", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.083, bpm)
keypress("T", x, bpm)
rest(0.167, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
rest(0.167, bpm)
keypress("O", x, bpm)
rest(0.083, bpm)
keypress("q", x, bpm)
rest(0.083, bpm)
keypress("O", x, bpm)
rest(0.167, bpm)
keypress("8", x, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
rest(0.167, bpm)
keypress("i", x, bpm)
rest(0.167, bpm)
keypress("Y", x, bpm)
rest(0.167, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("Y", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.167, bpm)
keypress("O", x, bpm)
rest(0.167, bpm)
keypress("i", x, bpm)
rest(0.167, bpm)
keypress("i", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("i", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("%", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(3.5, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
rest(0.73, bpm)
keypress("%", x, bpm)
keypress("@", x, bpm)
rest(0.73, bpm)
keypress("!", x, bpm)
keypress("@", x, bpm)
rest(0.973, bpm)
keypress("W", x, bpm)
keypress("@", x, bpm)
rest(0.243, bpm)
keypress("W", x, bpm)
rest(0.243, bpm)
keypress("Y", x, bpm)
keypress("!", x, bpm)
rest(0.243, bpm)
keypress("@", x, bpm)
rest(0.243, bpm)
keypress("E", x, bpm)
rest(0.243, bpm)
keypress("W", x, bpm)
keypress("@", x, bpm)
rest(0.243, bpm)
keypress("!", x, bpm)
keypress("@", x, bpm)
rest(0.73, bpm)
keypress("%", x, bpm)
keypress("@", x, bpm)
rest(0.73, bpm)
keypress("@", x, bpm)
rest(0.973, bpm)
keypress("W", x, bpm)
keypress("@", x, bpm)
rest(0.243, bpm)
keypress("W", x, bpm)
rest(0.243, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
rest(0.487, bpm)
keypress("E", x, bpm)
rest(0.243, bpm)
keypress("W", x, bpm)
rest(0.243, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
rest(0.73, bpm)
keypress("%", x, bpm)
keypress("@", x, bpm)
rest(0.243, bpm)
keypress("t", x, bpm)
rest(0.243, bpm)
keypress("E", x, bpm)
rest(0.243, bpm)
keypress("t", x, bpm)
keypress("!", x, bpm)
keypress("@", x, bpm)
rest(0.243, bpm)
keypress("E", x, bpm)
rest(0.243, bpm)
keypress("t", x, bpm)
rest(0.243, bpm)
keypress("E", x, bpm)
rest(0.243, bpm)
keypress("t", x, bpm)
keypress("@", x, bpm)
rest(0.243, bpm)
keypress("E", x, bpm)
rest(0.243, bpm)
keypress("t", x, bpm)
keypress("!", x, bpm)
rest(0.243, bpm)
keypress("E", x, bpm)
keypress("@", x, bpm)
rest(0.73, bpm)
keypress("!", x, bpm)
keypress("@", x, bpm)
rest(0.73, bpm)
keypress("%", x, bpm)
keypress("@", x, bpm)
rest(0.73, bpm)
keypress("@", x, bpm)
rest(0.973, bpm)
keypress("W", x, bpm)
keypress("@", x, bpm)
rest(0.243, bpm)
keypress("W", x, bpm)
rest(0.243, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
rest(0.487, bpm)
keypress("E", x, bpm)
rest(0.243, bpm)
keypress("W", x, bpm)
rest(0.243, bpm)
keypress("r", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("@", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.73, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.243, bpm)
keypress("t", x, bpm)
rest(0.243, bpm)
keypress("E", x, bpm)
rest(0.243, bpm)
keypress("t", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.243, bpm)
keypress("E", x, bpm)
rest(0.243, bpm)
keypress("t", x, bpm)
rest(0.243, bpm)
keypress("E", x, bpm)
rest(0.243, bpm)
keypress("t", x, bpm)
keypress("@", x, bpm)
rest(0.243, bpm)
keypress("E", x, bpm)
rest(0.243, bpm)
keypress("t", x, bpm)
keypress("!", x, bpm)
rest(0.243, bpm)
keypress("E", x, bpm)
keypress("@", x, bpm)
rest(0.243, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.243, bpm)
keypress("@", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.243, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
keypress("O", x, bpm)
keypress("t", x, bpm)
keypress("@", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.73, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
keypress("@", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.243, bpm)
keypress("t", x, bpm)
rest(0.243, bpm)
keypress("E", x, bpm)
rest(0.243, bpm)
keypress("t", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("P", x, bpm)
keypress("W", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.243, bpm)
keypress("E", x, bpm)
rest(0.243, bpm)
keypress("t", x, bpm)
rest(0.243, bpm)
keypress("E", x, bpm)
rest(0.243, bpm)
keypress("W", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.243, bpm)
keypress("W", x, bpm)
rest(0.243, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
keypress("w", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.487, bpm)
keypress("E", x, bpm)
rest(0.243, bpm)
keypress("W", x, bpm)
rest(0.243, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("@", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.487, bpm)
keypress("W", x, bpm)
rest(0.243, bpm)
keypress("W", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.243, bpm)
keypress("Y", x, bpm)
rest(0.487, bpm)
keypress("E", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.243, bpm)
keypress("W", x, bpm)
rest(0.73, bpm)
keypress("W", x, bpm)
keypress("@", x, bpm)
rest(0.243, bpm)
keypress("W", x, bpm)
rest(0.243, bpm)
keypress("Y", x, bpm)
keypress("!", x, bpm)
rest(0.243, bpm)
keypress("@", x, bpm)
rest(0.243, bpm)
keypress("E", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.243, bpm)
keypress("W", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.243, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
keypress("O", x, bpm)
keypress("t", x, bpm)
keypress("@", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.73, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
keypress("@", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.243, bpm)
keypress("t", x, bpm)
rest(0.243, bpm)
keypress("E", x, bpm)
rest(0.243, bpm)
keypress("t", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("P", x, bpm)
keypress("W", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.243, bpm)
keypress("E", x, bpm)
rest(0.243, bpm)
keypress("t", x, bpm)
rest(0.243, bpm)
keypress("E", x, bpm)
rest(0.243, bpm)
keypress("W", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.243, bpm)
keypress("W", x, bpm)
rest(0.243, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
keypress("w", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.487, bpm)
keypress("E", x, bpm)
rest(0.243, bpm)
keypress("W", x, bpm)
rest(0.243, bpm)
keypress("r", x, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
rest(0.162, bpm)
keypress("t", x, bpm)
rest(0.162, bpm)
keypress("E", x, bpm)
rest(0.162, bpm)
keypress("t", x, bpm)
rest(0.162, bpm)
keypress("t", x, bpm)
rest(0.081, bpm)
keypress("%", x, bpm)
keypress("@", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
rest(0.081, bpm)
keypress("E", x, bpm)
rest(0.162, bpm)
keypress("t", x, bpm)
rest(0.162, bpm)
keypress("E", x, bpm)
rest(0.324, bpm)
keypress("!", x, bpm)
keypress("@", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("S", x, bpm)
rest(0.487, bpm)
keypress("W", x, bpm)
rest(0.162, bpm)
keypress("W", x, bpm)
rest(0.162, bpm)
keypress("W", x, bpm)
rest(0.162, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
rest(0.162, bpm)
keypress("Y", x, bpm)
rest(0.162, bpm)
keypress("Y", x, bpm)
rest(0.162, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)
rest(0.243, bpm)
keypress("@", x, bpm)
rest(0.243, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.243, bpm)
keypress("@", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.243, bpm)
keypress("!", x, bpm)
keypress("@", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
keypress("i", x, bpm)
keypress("S", x, bpm)
keypress("l", x, bpm)
rest(0.73, bpm)
keypress("%", x, bpm)
keypress("@", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
rest(0.73, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
rest(0.973, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.243, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
rest(0.243, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.487, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
rest(0.243, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
rest(0.243, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
keypress("@", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
rest(0.162, bpm)
keypress("t", x, bpm)
rest(0.162, bpm)
keypress("E", x, bpm)
rest(0.162, bpm)
keypress("t", x, bpm)
rest(0.162, bpm)
keypress("t", x, bpm)
rest(0.081, bpm)
keypress("%", x, bpm)
keypress("@", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
rest(0.081, bpm)
keypress("E", x, bpm)
rest(0.162, bpm)
keypress("t", x, bpm)
rest(0.162, bpm)
keypress("E", x, bpm)
rest(0.324, bpm)
keypress("!", x, bpm)
keypress("@", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("S", x, bpm)
rest(0.487, bpm)
keypress("W", x, bpm)
rest(0.162, bpm)
keypress("W", x, bpm)
rest(0.162, bpm)
keypress("W", x, bpm)
rest(0.162, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
rest(0.162, bpm)
keypress("Y", x, bpm)
rest(0.162, bpm)
keypress("Y", x, bpm)
rest(0.162, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)
rest(0.243, bpm)
keypress("@", x, bpm)
rest(0.243, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.243, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.243, bpm)
keypress("!", x, bpm)
keypress("@", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
keypress("i", x, bpm)
keypress("S", x, bpm)
keypress("l", x, bpm)
rest(0.73, bpm)
keypress("%", x, bpm)
keypress("@", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
rest(0.73, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
rest(0.973, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.243, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
rest(0.243, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.487, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
rest(0.243, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
rest(0.243, bpm)
keypress("r", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("@", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
rest(0.487, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
rest(0.243, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
rest(0.243, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
rest(0.487, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("S", x, bpm)
rest(0.243, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
rest(0.73, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
rest(0.243, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
rest(0.243, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("!", x, bpm)
rest(0.243, bpm)
keypress("@", x, bpm)
rest(0.243, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.243, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.243, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
keypress("O", x, bpm)
keypress("t", x, bpm)
keypress("@", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
keypress("i", x, bpm)
keypress("S", x, bpm)
keypress("l", x, bpm)
rest(0.73, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
keypress("@", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
rest(0.243, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
rest(0.243, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
rest(0.243, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("P", x, bpm)
keypress("W", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
rest(0.243, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
rest(0.243, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
rest(0.243, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
rest(0.243, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.243, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
rest(0.243, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
keypress("w", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.487, bpm)
keypress("E", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
rest(0.243, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.243, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("@", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
rest(0.487, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
rest(0.243, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
rest(0.243, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
rest(0.487, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("S", x, bpm)
rest(0.243, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
rest(0.73, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
rest(0.243, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
rest(0.243, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("!", x, bpm)
rest(0.243, bpm)
keypress("@", x, bpm)
rest(0.243, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.243, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.243, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
keypress("O", x, bpm)
keypress("t", x, bpm)
keypress("@", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
keypress("i", x, bpm)
keypress("S", x, bpm)
keypress("l", x, bpm)
rest(0.73, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
keypress("@", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
rest(0.243, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
rest(0.243, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
rest(0.243, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("P", x, bpm)
keypress("W", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
rest(0.243, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
rest(0.243, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
rest(0.243, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
rest(0.243, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.243, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
rest(0.243, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
keypress("w", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.487, bpm)
keypress("E", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
rest(0.243, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.243, bpm)
keypress("r", x, bpm)
keypress("2", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("@", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("S", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
keypress("!", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
keypress("O", x, bpm)
keypress("t", x, bpm)
keypress("@", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
keypress("i", x, bpm)
keypress("S", x, bpm)
keypress("l", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
keypress("@", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("P", x, bpm)
keypress("W", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
keypress("w", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("r", x, bpm)
keypress("2", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("@", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("S", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
keypress("!", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
keypress("O", x, bpm)
keypress("t", x, bpm)
keypress("@", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
keypress("i", x, bpm)
keypress("S", x, bpm)
keypress("l", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
keypress("@", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("P", x, bpm)
keypress("W", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
keypress("w", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("r", x, bpm)
keypress("2", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("@", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
keypress("!", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
keypress("O", x, bpm)
keypress("t", x, bpm)
keypress("@", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
keypress("i", x, bpm)
keypress("S", x, bpm)
keypress("l", x, bpm)
keypress("!", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
keypress("@", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("P", x, bpm)
keypress("W", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
keypress("@", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
keypress("w", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
keypress("@", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("r", x, bpm)
keypress("2", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("@", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
keypress("!", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
keypress("O", x, bpm)
keypress("t", x, bpm)
keypress("@", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
keypress("i", x, bpm)
keypress("S", x, bpm)
keypress("l", x, bpm)
keypress("!", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
keypress("@", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("2", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("P", x, bpm)
keypress("W", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
keypress("@", x, bpm)
rest(0.243, bpm)
keypress("2", x, bpm)
rest(0.73, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
rest(0.243, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
rest(0.243, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
rest(0.487, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
rest(0.243, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
rest(0.243, bpm)
keypress("q", x, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
rest(0.73, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
rest(0.73, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
rest(2.433, bpm)
keypress("*", x, bpm)
keypress("O", x, bpm)
keypress("t", x, bpm)
rest(0.73, bpm)
keypress("W", x, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
rest(0.73, bpm)
keypress("(", x, bpm)
keypress("P", x, bpm)
keypress("W", x, bpm)
rest(1.46, bpm)
keypress("w", x, bpm)
rest(0.973, bpm)
keypress("q", x, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
rest(0.73, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("D", x, bpm)
rest(0.73, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
rest(2.433, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.73, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
rest(0.73, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(2.433, bpm)
keypress("q", x, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
rest(0.73, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
rest(0.73, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
rest(2.433, bpm)
keypress("*", x, bpm)
keypress("O", x, bpm)
keypress("t", x, bpm)
rest(0.73, bpm)
keypress("W", x, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
rest(0.73, bpm)
keypress("(", x, bpm)
keypress("P", x, bpm)
keypress("W", x, bpm)
rest(1.46, bpm)
keypress("w", x, bpm)
rest(0.973, bpm)
keypress("q", x, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
rest(0.73, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("D", x, bpm)
rest(0.73, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
rest(2.433, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.73, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
rest(0.73, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
